module.exports = {
    gallery: [
        { name: '001',      img: '/img/Options/service-1.jpg'  },
        { name: '002',      img: '/img/Options/service-2.jpg'  },
        { name: '003',      img: '/img/Options/service-3.jpg'  },
        { name: '004',      img: '/img/Options/service-4.jpg'  },
        { name: '005' ,     img: '/img/Options/service-5.jpg'  },
        { name: '006',      img: '/img/Options/service-6.jpg'  },
        { name: '007',      img: '/img/Options/service-7.jpg'  },
        { name: '008',      img: '/img/Options/service-8.jpg'  },
        { name: '009',      img: '/img/Options/service-9.jpg'  },
        { name: '010',      img: '/img/Options/service-10.jpg'  },
        { name: '011',      img: '/img/Options/service-11.jpg'  },
        { name: '012',      img: '/img/Options/service-12.jpg'  },
        { name: '013',      img: '/img/Options/service-13.jpg'  },
        { name: '014',      img: '/img/Options/service-14.jpg'  },
        { name: '015',      img: '/img/Options/service-15.jpg'  },
        { name: '016',      img: '/img/Options/service-16.jpg'  },
        { name: '017',      img: '/img/Options/service-17.jpg'  },
        { name: '018',      img: '/img/Options/service-18.jpg'  },
        { name: '019',      img: '/img/Options/service-19.jpg'  },
        { name: '020',      img: '/img/Options/service-20.jpg'  },
    ],  
}