module.exports = {
    gallery: [
        { name: '001',      img: '/img/Options/service-1.jpg',  category: 'Ammenities', description: 'A description of our service...'},
        { name: '002',      img: '/img/Options/service-2.jpg',  category: 'Hot Tub', description: 'A description of our service...'  },
        { name: '003',      img: '/img/Options/service-3.jpg',  category: 'Hot Tub', description: 'A description of our service...'  },
        { name: '004',      img: '/img/Options/service-4.jpg',  category: 'Massage', description: 'A description of our service...'  },
        { name: '005' ,     img: '/img/Options/service-5.jpg',  category: 'Hot Tub', description: 'A description of our service...'   },
        { name: '006',      img: '/img/Options/service-6.jpg',  category: 'Ammenities', description: 'A description of our service...'  },
        { name: '007',      img: '/img/Options/service-7.jpg',  category: 'Hot Tub', description: 'A description of our service...'   },
        { name: '008',      img: '/img/Options/service-8.jpg',  category: 'Massage', description: 'A description of our service...'   },
        { name: '009',      img: '/img/Options/service-9.jpg' , category: 'Hot Tub', description: 'A description of our service...'  },
        { name: '010',      img: '/img/Options/service-10.jpg', category: 'Ammenities', description: 'A description of our service...'   },
        { name: '011',      img: '/img/Options/service-11.jpg', category: 'Ammenities', description: 'A description of our service...'  },
        { name: '012',      img: '/img/Options/service-12.jpg', category: 'Hot Tub', description: 'A description of our service...'  },
        { name: '013',      img: '/img/Options/service-13.jpg', category: 'Hot Tub', description: 'A description of our service...'   },
        { name: '014',      img: '/img/Options/service-14.jpg', category: 'Hot Tub', description: 'A description of our service...'   },
        { name: '015',      img: '/img/Options/service-15.jpg', category: 'Ammenities', description: 'A description of our service...'  },
        { name: '016',      img: '/img/Options/service-16.jpg', category: 'Massage', description: 'A description of our service...'  },
        { name: '017',      img: '/img/Options/service-17.jpg', category: 'Massage', description: 'A description of our service...' },
        { name: '018',      img: '/img/Options/service-18.jpg' , category: 'Hot Tub', description: 'A description of our service...' },
        { name: '019',      img: '/img/Options/service-19.jpg', category: 'Hot Tub', description: 'A description of our service...'  },
        { name: '020',      img: '/img/Options/service-20.jpg' , category: 'Ammenities', description: 'A description of our service...' },
    ],  
    categories: ['All', 'Massage', 'Hot Tub', 'Ammenities']
}